version: '3'

services:
  app:
    container_name: "${DOCKER_PREFIX}_app"
    image: "${DOCKER_PREFIX}_app"
    restart: unless-stopped
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
